trigger:
  branches:
    include:
      - main

jobs:
  - job: deploy
    displayName: 'Deploy to Salesforce UatOrg'
    pool:
      name: 'mess'  # Use your self-hosted agent pool

    steps:
      - checkout: self
        displayName: 'Checkout repository'

      - script: |
          echo "Adding Salesforce CLI to PATH..."
          echo "##vso[task.setvariable variable=PATH]\"C:\Program Files\Salesforce CLI\bin\";$(PATH)"
          echo "Updated PATH: $(PATH)"
          sfdx --version  # Verify Salesforce CLI is available
        displayName: 'Set Salesforce CLI Path'

      # Authenticate to UatOrg using web login
      - script: |
          echo "Authenticating to UatOrg using web login..."
          sfdx auth:web:login --setalias uat --instanceurl https://taruitsolutions-6d-dev-ed.develop.my.salesforce.com/
        displayName: 'Authenticate to UatOrg'

      # Deploy to UatOrg using sfdx command
      - script: |
          echo "Deploying to UatOrg..."
          sf project deploy start --source-dir force-app --target-org uat
        displayName: 'Deploy to UatOrg'
